from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from app.database import get_db
from app.auth import get_current_user
from app import models

router = APIRouter(prefix="/guide", tags=["Local Guide"])

# ── University → city mapping ──────────────────────────────────────────────
UNIVERSITY_CITY = {
    "Aberystwyth University": "Aberystwyth",
    "Anglia Ruskin University": "Cambridge",
    "Arden University": "Birmingham",
    "Arts University Bournemouth": "Bournemouth",
    "Aston University": "Birmingham",
    "Bangor University": "Bangor",
    "Bath Spa University": "Bath",
    "Birkbeck, University of London": "London",
    "Birmingham City University": "Birmingham",
    "Bishop Grosseteste University": "Lincoln",
    "Bournemouth University": "Bournemouth",
    "BPP University": "London",
    "University of Bradford": "Bradford",
    "University of Brighton": "Brighton",
    "University of Bristol": "Bristol",
    "Brunel University London": "London",
    "Buckinghamshire New University": "High Wycombe",
    "University of Cambridge": "Cambridge",
    "Canterbury Christ Church University": "Canterbury",
    "Cardiff Metropolitan University": "Cardiff",
    "Cardiff University": "Cardiff",
    "University of Central Lancashire": "Preston",
    "University of Chester": "Chester",
    "University of Chichester": "Chichester",
    "City, University of London": "London",
    "Coventry University": "Coventry",
    "Cranfield University": "Cranfield",
    "University of Cumbria": "Carlisle",
    "De Montfort University": "Leicester",
    "University of Derby": "Derby",
    "University of Dundee": "Dundee",
    "Durham University": "Durham",
    "University of East Anglia": "Norwich",
    "University of East London": "London",
    "Edge Hill University": "Ormskirk",
    "Edinburgh Napier University": "Edinburgh",
    "University of Edinburgh": "Edinburgh",
    "University of Essex": "Colchester",
    "University of Exeter": "Exeter",
    "Falmouth University": "Falmouth",
    "University of Glasgow": "Glasgow",
    "Glasgow Caledonian University": "Glasgow",
    "University of Gloucestershire": "Cheltenham",
    "Goldsmiths, University of London": "London",
    "University of Greenwich": "London",
    "Harper Adams University": "Newport",
    "Heriot-Watt University": "Edinburgh",
    "University of Hertfordshire": "Hatfield",
    "University of the Highlands and Islands": "Inverness",
    "University of Huddersfield": "Huddersfield",
    "University of Hull": "Hull",
    "Imperial College London": "London",
    "Keele University": "Keele",
    "University of Kent": "Canterbury",
    "King's College London": "London",
    "Kingston University": "London",
    "Lancaster University": "Lancaster",
    "University of Leeds": "Leeds",
    "Leeds Beckett University": "Leeds",
    "Leeds Arts University": "Leeds",
    "Leeds Trinity University": "Leeds",
    "University of Leicester": "Leicester",
    "University of Lincoln": "Lincoln",
    "University of Liverpool": "Liverpool",
    "Liverpool Hope University": "Liverpool",
    "Liverpool John Moores University": "Liverpool",
    "London Metropolitan University": "London",
    "London School of Economics and Political Science": "London",
    "London South Bank University": "London",
    "Loughborough University": "Loughborough",
    "University of Manchester": "Manchester",
    "Manchester Metropolitan University": "Manchester",
    "Middlesex University": "London",
    "Newcastle University": "Newcastle",
    "Northumbria University": "Newcastle",
    "Norwich University of the Arts": "Norwich",
    "University of Nottingham": "Nottingham",
    "Nottingham Trent University": "Nottingham",
    "Open University": "Milton Keynes",
    "University of Oxford": "Oxford",
    "Oxford Brookes University": "Oxford",
    "University of Plymouth": "Plymouth",
    "University of Portsmouth": "Portsmouth",
    "Queen Margaret University": "Edinburgh",
    "Queen Mary University of London": "London",
    "Queen's University Belfast": "Belfast",
    "University of Reading": "Reading",
    "Ravensbourne University London": "London",
    "Robert Gordon University": "Aberdeen",
    "University of Roehampton": "London",
    "Royal College of Art": "London",
    "Royal Holloway, University of London": "Egham",
    "University of Salford": "Manchester",
    "University of Sheffield": "Sheffield",
    "Sheffield Hallam University": "Sheffield",
    "SOAS University of London": "London",
    "Solent University": "Southampton",
    "University of South Wales": "Cardiff",
    "University of Southampton": "Southampton",
    "University of St Andrews": "St Andrews",
    "St George's, University of London": "London",
    "St Mary's University, Twickenham": "London",
    "Staffordshire University": "Stoke-on-Trent",
    "University of Stirling": "Stirling",
    "University of Strathclyde": "Glasgow",
    "University of Suffolk": "Ipswich",
    "University of Sunderland": "Sunderland",
    "University of Surrey": "Guildford",
    "University of Sussex": "Brighton",
    "Swansea University": "Swansea",
    "Teesside University": "Middlesbrough",
    "University of the Arts London": "London",
    "University of the West of England": "Bristol",
    "University of the West of Scotland": "Paisley",
    "Ulster University": "Belfast",
    "University College London": "London",
    "University of Warwick": "Coventry",
    "University of West London": "London",
    "University of Westminster": "London",
    "University of Winchester": "Winchester",
    "University of Wolverhampton": "Wolverhampton",
    "University of Worcester": "Worcester",
    "Wrexham University": "Wrexham",
    "University of York": "York",
    "York St John University": "York",
}

# ── Curated listings per city ──────────────────────────────────────────────
CITY_LISTINGS = {
    "London": [
        {"name": "NHS Walk-In Centre, Soho", "category": "GP", "distance": "Varies", "rating": 4.0, "description": "Central London walk-in for urgent care. No registration needed."},
        {"name": "Student Health Service (UCL)", "category": "GP", "distance": "Varies", "rating": 4.3, "description": "Many London unis have their own GP service — check with your university."},
        {"name": "Tesco Metro", "category": "Supermarket", "distance": "Varies", "rating": 3.9, "description": "Small-format Tesco stores found across every London neighbourhood."},
        {"name": "Aldi / Lidl", "category": "Supermarket", "distance": "Varies", "rating": 4.3, "description": "Budget supermarkets expanding across London. Best value for weekly shops."},
        {"name": "Sainsbury's Local", "category": "Supermarket", "distance": "Varies", "rating": 4.0, "description": "Convenient for quick top-ups. Nectar card for student savings."},
        {"name": "Boots Pharmacy", "category": "Pharmacy", "distance": "Varies", "rating": 4.1, "description": "NHS prescriptions and health advice. Branches on most high streets."},
        {"name": "Superdrug", "category": "Pharmacy", "distance": "Varies", "rating": 4.0, "description": "Affordable health & beauty plus pharmacy services. Student discount available."},
        {"name": "Dishoom", "category": "Restaurant", "distance": "Varies", "rating": 4.6, "description": "Beloved Indian restaurant chain. Try the bacon naan roll at breakfast."},
        {"name": "Tortilla", "category": "Restaurant", "distance": "Varies", "rating": 4.2, "description": "Build-your-own burritos and bowls. Student portions at fair prices."},
        {"name": "Franco Manca", "category": "Restaurant", "distance": "Varies", "rating": 4.4, "description": "Sourdough pizza from £6.95. One of the best value meals in London."},
        {"name": "TfL Underground", "category": "Transport", "distance": "Varies", "rating": 4.2, "description": "Get a Student Oyster for 30% off Travelcards. Contactless also accepted."},
        {"name": "Santander Cycles", "category": "Transport", "distance": "Varies", "rating": 4.0, "description": "£2 per ride or annual membership. Great for short trips across central London."},
        {"name": "National Express Coach", "category": "Transport", "distance": "Varies", "rating": 3.8, "description": "Victoria Coach Station connects to all UK cities. Student coachcard saves ⅓."},
    ],
    "Manchester": [
        {"name": "University Health Centre", "category": "GP", "distance": "0.3 mi", "rating": 4.1, "description": "Dedicated GP for students in the university quarter. Register on arrival."},
        {"name": "Fallowfield Health Centre", "category": "GP", "distance": "0.5 mi", "rating": 4.0, "description": "Popular with students living in Fallowfield. Walk-in slots available."},
        {"name": "Aldi Fallowfield", "category": "Supermarket", "distance": "0.4 mi", "rating": 4.3, "description": "Budget supermarket in the student heartland. Unbeatable weekly shop prices."},
        {"name": "Lidl Oxford Road", "category": "Supermarket", "distance": "0.3 mi", "rating": 4.2, "description": "Central location near campus. Great bakery section for cheap lunches."},
        {"name": "Asda Hulme", "category": "Supermarket", "distance": "0.8 mi", "rating": 4.1, "description": "Large supermarket with wide selection. Delivery slots from £1."},
        {"name": "Boots Oxford Road", "category": "Pharmacy", "distance": "0.2 mi", "rating": 4.1, "description": "NHS prescriptions and flu jabs. Right on the student corridor."},
        {"name": "Krunchy Fried Chicken", "category": "Restaurant", "distance": "0.3 mi", "rating": 4.0, "description": "Manchester student institution. Cheap, filling, open late."},
        {"name": "Curry Mile (Rusholme)", "category": "Restaurant", "distance": "0.6 mi", "rating": 4.5, "description": "Famous strip of South Asian restaurants. Incredible food from £5."},
        {"name": "Pieminister", "category": "Restaurant", "distance": "0.7 mi", "rating": 4.3, "description": "Gourmet pies with mash and gravy. Proper comfort food."},
        {"name": "Stagecoach Magic Bus", "category": "Transport", "distance": "0.1 mi", "rating": 3.9, "description": "£1 student bus fare on the Magic Bus route. Covers Fallowfield to city centre."},
        {"name": "Manchester Piccadilly Station", "category": "Transport", "distance": "0.8 mi", "rating": 4.1, "description": "Main rail hub. 2 hours to London, 1 hour to Leeds. Get a Railcard."},
        {"name": "Metrolink Tram", "category": "Transport", "distance": "0.4 mi", "rating": 4.0, "description": "Tram network across Greater Manchester. Contactless payment accepted."},
    ],
    "Birmingham": [
        {"name": "University Medical Practice", "category": "GP", "distance": "0.2 mi", "rating": 4.1, "description": "On-campus GP for university students. Book online via the NHS app."},
        {"name": "Selly Oak Health Centre", "category": "GP", "distance": "0.5 mi", "rating": 4.0, "description": "Student-friendly GP in the main student area. Register in freshers week."},
        {"name": "Aldi Selly Oak", "category": "Supermarket", "distance": "0.4 mi", "rating": 4.2, "description": "Budget supermarket in the student quarter. Weekly specials are unmissable."},
        {"name": "Sainsbury's Selly Oak", "category": "Supermarket", "distance": "0.3 mi", "rating": 4.0, "description": "Medium-sized store covering all essentials. Open until 11pm."},
        {"name": "Boots Pharmacy", "category": "Pharmacy", "distance": "0.4 mi", "rating": 4.0, "description": "Prescription collection and health advice on the Bristol Road."},
        {"name": "Selly Sausage", "category": "Restaurant", "distance": "0.3 mi", "rating": 4.5, "description": "Legendary student café. All-day brunch and great coffee."},
        {"name": "Jailbird", "category": "Restaurant", "distance": "0.5 mi", "rating": 4.3, "description": "Fried chicken restaurant popular with students. Meal deals available."},
        {"name": "National Express West Midlands", "category": "Transport", "distance": "0.1 mi", "rating": 3.9, "description": "Frequent buses from Selly Oak to city centre. Student bus pass available."},
        {"name": "Birmingham New Street Station", "category": "Transport", "distance": "2.0 mi", "rating": 4.2, "description": "Major rail hub. 1h20 to London Euston. Grand Central shopping above."},
    ],
    "Edinburgh": [
        {"name": "University Health Service", "category": "GP", "distance": "0.2 mi", "rating": 4.2, "description": "Dedicated student GP on campus. Scotland offers free prescriptions."},
        {"name": "Stockbridge Health Centre", "category": "GP", "distance": "0.8 mi", "rating": 4.1, "description": "Well-regarded practice near the New Town. Accepting new patients."},
        {"name": "Aldi Nicolson Street", "category": "Supermarket", "distance": "0.3 mi", "rating": 4.2, "description": "Central budget supermarket near the Old Town campus buildings."},
        {"name": "Lidl Chesser", "category": "Supermarket", "distance": "1.0 mi", "rating": 4.1, "description": "Great value groceries. Worth the trip for a big weekly shop."},
        {"name": "Sainsbury's Local", "category": "Supermarket", "distance": "0.2 mi", "rating": 3.9, "description": "Multiple locations near campus for quick convenience shopping."},
        {"name": "Boots Pharmacy", "category": "Pharmacy", "distance": "0.3 mi", "rating": 4.0, "description": "NHS prescriptions are FREE in Scotland. Collect from any pharmacy."},
        {"name": "Mosque Kitchen", "category": "Restaurant", "distance": "0.2 mi", "rating": 4.5, "description": "Edinburgh student legend. Huge portions of curry and rice for under £7."},
        {"name": "Civerinos", "category": "Restaurant", "distance": "0.4 mi", "rating": 4.4, "description": "New York-style pizza slices. Quick, cheap, and excellent."},
        {"name": "Oink", "category": "Restaurant", "distance": "0.3 mi", "rating": 4.5, "description": "Hog roast rolls on the Grassmarket. A must-try Edinburgh experience."},
        {"name": "Lothian Buses", "category": "Transport", "distance": "0.1 mi", "rating": 4.3, "description": "Excellent bus network. £1.80 single fare, contactless accepted."},
        {"name": "Edinburgh Waverley Station", "category": "Transport", "distance": "0.4 mi", "rating": 4.2, "description": "Central station with trains to Glasgow (50 min), London (4.5 hrs)."},
    ],
    "Glasgow": [
        {"name": "University Health Service", "category": "GP", "distance": "0.2 mi", "rating": 4.1, "description": "On-campus GP. Remember — prescriptions are free in Scotland!"},
        {"name": "Woodlands Health Centre", "category": "GP", "distance": "0.6 mi", "rating": 4.0, "description": "Friendly practice in the West End, popular with students."},
        {"name": "Lidl Byres Road", "category": "Supermarket", "distance": "0.3 mi", "rating": 4.2, "description": "Budget supermarket in the heart of the student West End."},
        {"name": "Tesco Metro Byres Road", "category": "Supermarket", "distance": "0.2 mi", "rating": 3.9, "description": "Convenient for daily essentials. Open late."},
        {"name": "Boots Pharmacy", "category": "Pharmacy", "distance": "0.3 mi", "rating": 4.0, "description": "Free NHS prescriptions in Scotland. Health advice and flu jabs."},
        {"name": "Baffo Pizza", "category": "Restaurant", "distance": "0.4 mi", "rating": 4.5, "description": "Excellent pizza in the West End. Student-friendly prices."},
        {"name": "Ketchup", "category": "Restaurant", "distance": "0.3 mi", "rating": 4.3, "description": "Ashton Lane restaurant. Burgers, cocktails, and a great atmosphere."},
        {"name": "First Glasgow Buses", "category": "Transport", "distance": "0.1 mi", "rating": 3.8, "description": "Extensive bus network. First Bus app for mobile tickets."},
        {"name": "Glasgow Queen Street Station", "category": "Transport", "distance": "0.7 mi", "rating": 4.1, "description": "Trains to Edinburgh (50 min) and the Highlands."},
        {"name": "Glasgow Subway", "category": "Transport", "distance": "0.5 mi", "rating": 4.2, "description": "Simple circular line connecting the West End to the city centre. £1.75 single."},
    ],
    "Leeds": [
        {"name": "Leeds Student Medical Practice", "category": "GP", "distance": "0.3 mi", "rating": 4.2, "description": "Dedicated GP for students near campus. Register online before arriving."},
        {"name": "Hyde Park Surgery", "category": "GP", "distance": "0.5 mi", "rating": 4.0, "description": "Popular with students living in Hyde Park and Headingley."},
        {"name": "Aldi Hyde Park", "category": "Supermarket", "distance": "0.4 mi", "rating": 4.3, "description": "Budget supermarket in the main student neighbourhood."},
        {"name": "Morrisons Headingley", "category": "Supermarket", "distance": "0.7 mi", "rating": 4.1, "description": "Full-size supermarket with great value. Student essentials covered."},
        {"name": "Boots Pharmacy", "category": "Pharmacy", "distance": "0.3 mi", "rating": 4.1, "description": "NHS prescriptions and health advice near campus."},
        {"name": "MyLahore", "category": "Restaurant", "distance": "0.8 mi", "rating": 4.5, "description": "Legendary Leeds restaurant. Huge portions of South Asian food."},
        {"name": "Headingley Taps", "category": "Restaurant", "distance": "0.7 mi", "rating": 4.2, "description": "Student pub with decent food and a beer garden. Quiz nights."},
        {"name": "First Leeds Buses", "category": "Transport", "distance": "0.1 mi", "rating": 3.8, "description": "Frequent buses along the Otley Road student corridor."},
        {"name": "Leeds Station", "category": "Transport", "distance": "1.0 mi", "rating": 4.2, "description": "Major hub. 2h15 to London, 1h to Manchester. Get a Railcard."},
    ],
    "Bristol": [
        {"name": "University Health Centre", "category": "GP", "distance": "0.2 mi", "rating": 4.1, "description": "On-campus GP service for University of Bristol students."},
        {"name": "Stokes Croft Health Centre", "category": "GP", "distance": "0.6 mi", "rating": 4.0, "description": "Community GP accepting student registrations."},
        {"name": "Aldi Bedminster", "category": "Supermarket", "distance": "0.8 mi", "rating": 4.2, "description": "Budget supermarket south of the river. Worth the walk."},
        {"name": "Tesco Metro Park Street", "category": "Supermarket", "distance": "0.2 mi", "rating": 3.9, "description": "Central location near the university precinct. Handy for quick shops."},
        {"name": "Boots Pharmacy", "category": "Pharmacy", "distance": "0.3 mi", "rating": 4.0, "description": "Broadmead branch with full pharmacy services."},
        {"name": "St Nicholas Market", "category": "Restaurant", "distance": "0.4 mi", "rating": 4.6, "description": "Street food market with global cuisines. £5-8 for a filling lunch."},
        {"name": "The Thali Café", "category": "Restaurant", "distance": "0.5 mi", "rating": 4.4, "description": "Indian thali plates at student-friendly prices. A Bristol institution."},
        {"name": "First West of England Buses", "category": "Transport", "distance": "0.1 mi", "rating": 3.7, "description": "Main bus operator. Student annual pass available."},
        {"name": "Bristol Temple Meads Station", "category": "Transport", "distance": "1.2 mi", "rating": 4.1, "description": "1h40 to London Paddington. Direct trains to Cardiff, Exeter, Birmingham."},
    ],
    "Nottingham": [
        {"name": "Cripps Health Centre", "category": "GP", "distance": "0.2 mi", "rating": 4.2, "description": "University of Nottingham's campus GP. One of the largest student practices in the UK."},
        {"name": "Unity Surgery", "category": "GP", "distance": "0.5 mi", "rating": 4.0, "description": "City-centre GP popular with NTU students. Online booking available."},
        {"name": "Lidl Dunkirk", "category": "Supermarket", "distance": "0.4 mi", "rating": 4.2, "description": "Budget supermarket near University Park campus."},
        {"name": "Sainsbury's Castle Boulevard", "category": "Supermarket", "distance": "0.6 mi", "rating": 4.0, "description": "Large store between the two universities. Click & collect available."},
        {"name": "Boots Pharmacy (Original Store)", "category": "Pharmacy", "distance": "0.8 mi", "rating": 4.3, "description": "Boots was founded in Nottingham! This is their flagship pharmacy."},
        {"name": "Annie's Burger Shack", "category": "Restaurant", "distance": "0.7 mi", "rating": 4.5, "description": "Over 30 burger options. A Nottingham student must-visit."},
        {"name": "Kayal", "category": "Restaurant", "distance": "0.6 mi", "rating": 4.4, "description": "South Indian restaurant. Excellent dosas and thalis at fair prices."},
        {"name": "Nottingham City Transport", "category": "Transport", "distance": "0.1 mi", "rating": 4.2, "description": "One of the UK's best bus networks. Student semester passes available."},
        {"name": "Nottingham Station", "category": "Transport", "distance": "1.0 mi", "rating": 4.1, "description": "1h50 to London St Pancras. Direct trains to Birmingham and Sheffield."},
        {"name": "Nottingham Express Transit (Tram)", "category": "Transport", "distance": "0.3 mi", "rating": 4.3, "description": "Modern tram connecting campus to city centre and beyond."},
    ],
    "Sheffield": [
        {"name": "University Health Service", "category": "GP", "distance": "0.2 mi", "rating": 4.1, "description": "Dedicated student GP near both universities. Register in freshers week."},
        {"name": "Aldi Ecclesall Road", "category": "Supermarket", "distance": "0.4 mi", "rating": 4.2, "description": "Budget supermarket on the main student road."},
        {"name": "Morrisons Ecclesall Road", "category": "Supermarket", "distance": "0.3 mi", "rating": 4.1, "description": "Full-size supermarket in the student area. Open until 10pm."},
        {"name": "Boots Pharmacy", "category": "Pharmacy", "distance": "0.3 mi", "rating": 4.0, "description": "City centre branch with NHS prescription services."},
        {"name": "Bungalows & Bears", "category": "Restaurant", "distance": "0.5 mi", "rating": 4.3, "description": "Popular student hangout. Burgers, wings, and live music."},
        {"name": "Street Food Chef", "category": "Restaurant", "distance": "0.6 mi", "rating": 4.5, "description": "Mexican-inspired burritos. Cheap, filling, and delicious."},
        {"name": "Supertram", "category": "Transport", "distance": "0.3 mi", "rating": 4.1, "description": "Tram-train network across Sheffield. Student day passes available."},
        {"name": "Sheffield Station", "category": "Transport", "distance": "0.8 mi", "rating": 4.0, "description": "2h to London, 50 min to Leeds, 1h to Manchester."},
    ],
    "Liverpool": [
        {"name": "Brownlow Hill Health Centre", "category": "GP", "distance": "0.2 mi", "rating": 4.1, "description": "University of Liverpool student GP. On-campus appointments."},
        {"name": "Aldi London Road", "category": "Supermarket", "distance": "0.4 mi", "rating": 4.2, "description": "Budget supermarket near the university district."},
        {"name": "Tesco Express Bold Street", "category": "Supermarket", "distance": "0.3 mi", "rating": 3.9, "description": "City centre convenience store on one of Liverpool's best streets."},
        {"name": "Boots Pharmacy", "category": "Pharmacy", "distance": "0.3 mi", "rating": 4.0, "description": "NHS prescriptions and health advice. Multiple city centre branches."},
        {"name": "Bold Street Coffee", "category": "Restaurant", "distance": "0.3 mi", "rating": 4.4, "description": "Independent coffee shop and brunch spot. Student favourite."},
        {"name": "Nolita Cantina", "category": "Restaurant", "distance": "0.4 mi", "rating": 4.3, "description": "Tacos, burritos, and margaritas. Great student meal deals."},
        {"name": "Arriva Merseyside Buses", "category": "Transport", "distance": "0.1 mi", "rating": 3.8, "description": "Main bus operator. Solo student pass for unlimited travel."},
        {"name": "Liverpool Lime Street Station", "category": "Transport", "distance": "0.5 mi", "rating": 4.1, "description": "2h15 to London. Direct trains to Manchester (45 min) and Birmingham."},
        {"name": "Merseyrail", "category": "Transport", "distance": "0.4 mi", "rating": 4.2, "description": "Local rail network. Quick access to Wirral and Southport."},
    ],
    "Newcastle": [
        {"name": "University Health Centre", "category": "GP", "distance": "0.2 mi", "rating": 4.1, "description": "Campus GP for Newcastle and Northumbria students."},
        {"name": "Aldi Jesmond", "category": "Supermarket", "distance": "0.5 mi", "rating": 4.2, "description": "Budget supermarket in the main student neighbourhood."},
        {"name": "Sainsbury's Local Jesmond", "category": "Supermarket", "distance": "0.3 mi", "rating": 3.9, "description": "Convenient for daily essentials in the student area."},
        {"name": "Boots Pharmacy", "category": "Pharmacy", "distance": "0.3 mi", "rating": 4.0, "description": "Prescriptions and health advice near campus."},
        {"name": "Zapatista Burrito Bar", "category": "Restaurant", "distance": "0.4 mi", "rating": 4.4, "description": "Newcastle's favourite burrito spot. Fresh and filling."},
        {"name": "The Fat Hippo", "category": "Restaurant", "distance": "0.5 mi", "rating": 4.5, "description": "Gourmet burgers in Jesmond. A student treat."},
        {"name": "Tyne and Wear Metro", "category": "Transport", "distance": "0.3 mi", "rating": 4.2, "description": "Metro connects to coast, airport, and Sunderland. Student Pop card available."},
        {"name": "Newcastle Central Station", "category": "Transport", "distance": "0.7 mi", "rating": 4.2, "description": "3 hours to London. Cross Country trains to Edinburgh (1h30)."},
    ],
    "Cardiff": [
        {"name": "University Health Centre", "category": "GP", "distance": "0.2 mi", "rating": 4.1, "description": "Campus GP for Cardiff University students. Free NHS prescriptions in Wales!"},
        {"name": "Lidl City Road", "category": "Supermarket", "distance": "0.3 mi", "rating": 4.2, "description": "Budget supermarket on the popular student road."},
        {"name": "Tesco Express Cathays", "category": "Supermarket", "distance": "0.2 mi", "rating": 3.9, "description": "Quick convenience shop in the heart of student Cathays."},
        {"name": "Boots Pharmacy", "category": "Pharmacy", "distance": "0.4 mi", "rating": 4.0, "description": "Free prescriptions in Wales for all ages. Health advice available."},
        {"name": "City Road Kebabs", "category": "Restaurant", "distance": "0.2 mi", "rating": 4.2, "description": "Legendary student late-night spot. Affordable and filling."},
        {"name": "Chai Street", "category": "Restaurant", "distance": "0.5 mi", "rating": 4.4, "description": "Indian street food in the city centre. Excellent value."},
        {"name": "Cardiff Bus", "category": "Transport", "distance": "0.1 mi", "rating": 3.9, "description": "Main bus operator. Student passes for unlimited travel."},
        {"name": "Cardiff Central Station", "category": "Transport", "distance": "0.6 mi", "rating": 4.1, "description": "2 hours to London Paddington. Direct trains to Bristol (50 min)."},
    ],
    "Oxford": [
        {"name": "Jericho Health Centre", "category": "GP", "distance": "0.4 mi", "rating": 4.2, "description": "Popular GP near central Oxford. Accepting new student registrations."},
        {"name": "Tesco Metro Cowley Road", "category": "Supermarket", "distance": "0.5 mi", "rating": 3.9, "description": "Convenient location on Oxford's vibrant Cowley Road."},
        {"name": "Aldi Cowley", "category": "Supermarket", "distance": "0.8 mi", "rating": 4.2, "description": "Budget supermarket east of the city centre."},
        {"name": "Boots Pharmacy Cornmarket", "category": "Pharmacy", "distance": "0.2 mi", "rating": 4.0, "description": "Central Oxford pharmacy with full NHS services."},
        {"name": "The Covered Market", "category": "Restaurant", "distance": "0.3 mi", "rating": 4.5, "description": "Historic market with indie food stalls. Try Ben's Cookies."},
        {"name": "Atomic Burger", "category": "Restaurant", "distance": "0.6 mi", "rating": 4.4, "description": "Quirky burger joint on Cowley Road. A student institution."},
        {"name": "Oxford Bus Company", "category": "Transport", "distance": "0.1 mi", "rating": 4.0, "description": "City and park-and-ride buses. Student term pass available."},
        {"name": "Oxford Station", "category": "Transport", "distance": "0.5 mi", "rating": 4.0, "description": "1h to London Paddington. New Elizabeth line connection coming."},
    ],
    "Cambridge": [
        {"name": "Trumpington Street Medical Practice", "category": "GP", "distance": "0.3 mi", "rating": 4.2, "description": "Central GP accepting student registrations."},
        {"name": "Aldi Hills Road", "category": "Supermarket", "distance": "0.5 mi", "rating": 4.2, "description": "Budget supermarket south of the city centre."},
        {"name": "Sainsbury's Sidney Street", "category": "Supermarket", "distance": "0.2 mi", "rating": 4.0, "description": "Central supermarket right in the middle of Cambridge."},
        {"name": "Boots Pharmacy", "category": "Pharmacy", "distance": "0.2 mi", "rating": 4.1, "description": "NHS prescriptions on Petty Cury. Health advice available."},
        {"name": "Fitzbillies", "category": "Restaurant", "distance": "0.3 mi", "rating": 4.5, "description": "Iconic Cambridge bakery. Famous Chelsea buns since 1920."},
        {"name": "The Eagle Pub", "category": "Restaurant", "distance": "0.2 mi", "rating": 4.3, "description": "Historic pub where DNA discovery was announced. Classic British food."},
        {"name": "Stagecoach Citi Buses", "category": "Transport", "distance": "0.1 mi", "rating": 3.9, "description": "Bus network across Cambridge. Many students cycle instead!"},
        {"name": "Cambridge Station", "category": "Transport", "distance": "0.8 mi", "rating": 4.0, "description": "50 min to London Kings Cross. Bike parking for 3,000 cycles."},
    ],
    "Brighton": [
        {"name": "University of Brighton Health Centre", "category": "GP", "distance": "0.3 mi", "rating": 4.1, "description": "Student GP near campus. Register early as demand is high."},
        {"name": "Aldi London Road", "category": "Supermarket", "distance": "0.4 mi", "rating": 4.2, "description": "Budget supermarket near the city centre."},
        {"name": "Sainsbury's London Road", "category": "Supermarket", "distance": "0.3 mi", "rating": 4.0, "description": "Full-size supermarket in the student area."},
        {"name": "Boots Pharmacy", "category": "Pharmacy", "distance": "0.2 mi", "rating": 4.0, "description": "NHS prescriptions and health advice on North Street."},
        {"name": "Food for Friends", "category": "Restaurant", "distance": "0.4 mi", "rating": 4.4, "description": "Vegetarian restaurant in The Lanes. Brighton's veggie scene is incredible."},
        {"name": "Pompoko", "category": "Restaurant", "distance": "0.3 mi", "rating": 4.3, "description": "Japanese fast food. Huge portions for under £10. Student favourite."},
        {"name": "Brighton & Hove Buses", "category": "Transport", "distance": "0.1 mi", "rating": 4.1, "description": "Excellent bus network. Student Saver bus pass available."},
        {"name": "Brighton Station", "category": "Transport", "distance": "0.5 mi", "rating": 4.0, "description": "1 hour to London Victoria/London Bridge. Fast and frequent."},
    ],
    "Southampton": [
        {"name": "University Health Service", "category": "GP", "distance": "0.2 mi", "rating": 4.1, "description": "On-campus GP for Southampton students."},
        {"name": "Aldi Portswood", "category": "Supermarket", "distance": "0.3 mi", "rating": 4.2, "description": "Budget supermarket in the main student neighbourhood."},
        {"name": "Sainsbury's Portswood", "category": "Supermarket", "distance": "0.2 mi", "rating": 4.0, "description": "Convenient for Portswood-based students. Open late."},
        {"name": "Boots Pharmacy", "category": "Pharmacy", "distance": "0.3 mi", "rating": 4.0, "description": "NHS prescriptions and health services."},
        {"name": "Mango Thai", "category": "Restaurant", "distance": "0.4 mi", "rating": 4.4, "description": "Affordable Thai food in Portswood. Student favourite."},
        {"name": "Uni-link Bus", "category": "Transport", "distance": "0.1 mi", "rating": 4.2, "description": "Dedicated university bus service connecting campus to halls and city."},
        {"name": "Southampton Central Station", "category": "Transport", "distance": "1.2 mi", "rating": 4.0, "description": "1h20 to London Waterloo. Direct trains to Bournemouth and Winchester."},
    ],
    "Hatfield": [
        {"name": "Hatfield Health Centre", "category": "GP", "distance": "0.3 mi", "rating": 4.2, "description": "NHS GP surgery near campus. Book online or walk in for urgent care."},
        {"name": "Lister House Surgery", "category": "GP", "distance": "0.7 mi", "rating": 4.0, "description": "Friendly GP practice accepting new student registrations."},
        {"name": "Aldi Hatfield", "category": "Supermarket", "distance": "0.4 mi", "rating": 4.3, "description": "Budget-friendly supermarket. Great for weekly shops on a student budget."},
        {"name": "Tesco Express", "category": "Supermarket", "distance": "0.2 mi", "rating": 3.9, "description": "Convenient for quick top-ups. Open late for evening essentials."},
        {"name": "ASDA Hatfield", "category": "Supermarket", "distance": "1.1 mi", "rating": 4.1, "description": "Larger supermarket with wider selection and George clothing."},
        {"name": "Lidl Hatfield", "category": "Supermarket", "distance": "0.6 mi", "rating": 4.2, "description": "Affordable groceries with weekly changing special offers."},
        {"name": "Boots Pharmacy", "category": "Pharmacy", "distance": "0.3 mi", "rating": 4.1, "description": "NHS prescriptions, flu jabs, and health advice available."},
        {"name": "Lloyds Pharmacy", "category": "Pharmacy", "distance": "0.5 mi", "rating": 3.8, "description": "Prescription collection and over-the-counter medicines."},
        {"name": "Superdrug", "category": "Pharmacy", "distance": "0.4 mi", "rating": 4.0, "description": "Health & beauty products plus pharmacy services."},
        {"name": "Nando's Hatfield", "category": "Restaurant", "distance": "0.5 mi", "rating": 4.4, "description": "Popular peri-peri chicken spot. Student discount with NUS card."},
        {"name": "Papa Johns", "category": "Restaurant", "distance": "0.3 mi", "rating": 3.7, "description": "Pizza delivery and collection. Regular student deals available."},
        {"name": "Hatfield Kebab House", "category": "Restaurant", "distance": "0.4 mi", "rating": 4.0, "description": "Late-night kebabs and wraps. Student favourite after nights out."},
        {"name": "Subway", "category": "Restaurant", "distance": "0.2 mi", "rating": 3.9, "description": "Build your own sub. Affordable lunch option near campus."},
        {"name": "Uno Bus - Route 601", "category": "Transport", "distance": "0.1 mi", "rating": 4.0, "description": "Direct bus from campus to Hatfield station. Runs every 15 mins."},
        {"name": "Hatfield Railway Station", "category": "Transport", "distance": "0.8 mi", "rating": 3.8, "description": "25 mins to London Kings Cross. Get a 16-25 Railcard for savings."},
        {"name": "Uno Bus - Route 653", "category": "Transport", "distance": "0.1 mi", "rating": 3.9, "description": "Campus to St Albans route. Useful for weekend shopping trips."},
    ],
}


@router.get("/")
def get_guide(current_user: models.UserProfile = Depends(get_current_user)):
    university = current_user.university
    city = UNIVERSITY_CITY.get(university, None)
    listings = CITY_LISTINGS.get(city, []) if city else []
    return {
        "university": university,
        "city": city,
        "listings": listings,
    }
