from fastapi import APIRouter, Query

router = APIRouter(prefix="/universities", tags=["Universities"])

# Comprehensive list of UK universities and higher education institutions
UNIVERSITIES = [
    "Aberystwyth University",
    "Anglia Ruskin University",
    "Arden University",
    "Arts University Bournemouth",
    "Aston University",
    "Bangor University",
    "Bath Spa University",
    "Birkbeck, University of London",
    "Birmingham City University",
    "Bishop Grosseteste University",
    "Bournemouth University",
    "BPP University",
    "University of Bradford",
    "University of Brighton",
    "University of Bristol",
    "Brunel University London",
    "Buckinghamshire New University",
    "University of Cambridge",
    "Canterbury Christ Church University",
    "Cardiff Metropolitan University",
    "Cardiff University",
    "University of Central Lancashire",
    "University of Chester",
    "University of Chichester",
    "City, University of London",
    "Coventry University",
    "Cranfield University",
    "University of Cumbria",
    "De Montfort University",
    "University of Derby",
    "University of Dundee",
    "Durham University",
    "University of East Anglia",
    "University of East London",
    "Edge Hill University",
    "Edinburgh Napier University",
    "University of Edinburgh",
    "University of Essex",
    "University of Exeter",
    "Falmouth University",
    "University of Glasgow",
    "Glasgow Caledonian University",
    "University of Gloucestershire",
    "Goldsmiths, University of London",
    "University of Greenwich",
    "Harper Adams University",
    "Heriot-Watt University",
    "University of Hertfordshire",
    "University of the Highlands and Islands",
    "University of Huddersfield",
    "University of Hull",
    "Imperial College London",
    "Keele University",
    "University of Kent",
    "King's College London",
    "Kingston University",
    "Lancaster University",
    "University of Leeds",
    "Leeds Beckett University",
    "Leeds Arts University",
    "Leeds Trinity University",
    "University of Leicester",
    "University of Lincoln",
    "University of Liverpool",
    "Liverpool Hope University",
    "Liverpool John Moores University",
    "London Metropolitan University",
    "London School of Economics and Political Science",
    "London South Bank University",
    "Loughborough University",
    "University of Manchester",
    "Manchester Metropolitan University",
    "Middlesex University",
    "Newcastle University",
    "Northumbria University",
    "Norwich University of the Arts",
    "University of Nottingham",
    "Nottingham Trent University",
    "Open University",
    "University of Oxford",
    "Oxford Brookes University",
    "University of Plymouth",
    "University of Portsmouth",
    "Queen Margaret University",
    "Queen Mary University of London",
    "Queen's University Belfast",
    "University of Reading",
    "Ravensbourne University London",
    "Robert Gordon University",
    "University of Roehampton",
    "Royal College of Art",
    "Royal Holloway, University of London",
    "University of Salford",
    "University of Sheffield",
    "Sheffield Hallam University",
    "SOAS University of London",
    "Solent University",
    "University of South Wales",
    "University of Southampton",
    "University of St Andrews",
    "St George's, University of London",
    "St Mary's University, Twickenham",
    "Staffordshire University",
    "University of Stirling",
    "University of Strathclyde",
    "University of Suffolk",
    "University of Sunderland",
    "University of Surrey",
    "University of Sussex",
    "Swansea University",
    "Teesside University",
    "University of the Arts London",
    "University of the West of England",
    "University of the West of Scotland",
    "Ulster University",
    "University College London",
    "University of Warwick",
    "University of West London",
    "University of Westminster",
    "University of Winchester",
    "University of Wolverhampton",
    "University of Worcester",
    "Wrexham University",
    "University of York",
    "York St John University",
]


@router.get("/")
def list_universities(q: str = Query(default="", description="Search filter")):
    if not q:
        return UNIVERSITIES
    lower_q = q.lower()
    return [u for u in UNIVERSITIES if lower_q in u.lower()]
